## Some tests for embeddings

In [1]:
from relatio._embeddings import Embeddings

2022-03-02 18:13:13.360335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-02 18:13:13.360354: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
model = Embeddings("Gensim_pretrained", "glove-twitter-25")

In [3]:
model.get_vector('hello world')

array([-0.07471786,  0.02505993,  0.02053264, -0.02447855, -0.06980739,
       -0.06906321,  0.41509545,  0.14673875, -0.11010275, -0.00789614,
       -0.05643118,  0.02131934, -0.8449067 ,  0.03017564, -0.067238  ,
       -0.05375415,  0.03251113, -0.07668394, -0.02830008,  0.08461264,
       -0.08671761, -0.11458462, -0.12194471, -0.01001229, -0.02754919],
      dtype=float32)

In [4]:
model.get_vector("flkdsjfq hello")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:271: RuntimeWarning: No vector for token: flkdsjfq. It is not used to compute the embedding of: flkdsjfq hello.
  RuntimeWarning,


array([-0.18157847,  0.03022106,  0.07807245,  0.00119906, -0.11215979,
       -0.11807584,  0.4377542 ,  0.25030681, -0.13314278,  0.03140144,
       -0.09876093, -0.03344414, -0.67277026, -0.13460353, -0.03161349,
       -0.10583851,  0.11448286, -0.15264852, -0.19846898,  0.14529528,
       -0.04670635, -0.1365732 , -0.1552284 ,  0.1034966 , -0.11891694],
      dtype=float32)

In [5]:
model.get_vector("flkdsjfq")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:271: RuntimeWarning: No vector for token: flkdsjfq. It is not used to compute the embedding of: flkdsjfq.
  RuntimeWarning,
/home/germain/Desktop/narratives/relatio/.tox/dev/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/germain/Desktop/narratives/relatio/.tox/dev/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:132: RuntimeWarning: Unable to compute an embedding for phrase: flkdsjfq.
  RuntimeWarning,


In [6]:
model = Embeddings("Gensim_pretrained", "glove-twitter-25", sentences = ["this is a nice world","hello world","hello everybody"])

In [7]:
model.get_vector('hello world')

array([-0.07471786,  0.02505993,  0.02053264, -0.02447855, -0.06980739,
       -0.06906321,  0.41509548,  0.14673877, -0.11010276, -0.00789614,
       -0.05643119,  0.02131934, -0.8449067 ,  0.03017564, -0.06723801,
       -0.05375415,  0.03251113, -0.07668395, -0.02830008,  0.08461265,
       -0.08671761, -0.11458461, -0.12194471, -0.01001229, -0.02754919],
      dtype=float32)

In [8]:
model.get_vector("flkdsjfq hello")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:114: RuntimeWarning: No frequency information for token: flkdsjfq. It is not used to compute the SIF-embedding of phrase: flkdsjfq hello.
  RuntimeWarning,


array([-0.18157846,  0.03022106,  0.07807244,  0.00119906, -0.11215978,
       -0.11807583,  0.43775418,  0.2503068 , -0.13314278,  0.03140144,
       -0.09876093, -0.03344414, -0.6727702 , -0.13460352, -0.03161348,
       -0.10583849,  0.11448285, -0.15264851, -0.19846897,  0.14529528,
       -0.04670634, -0.13657318, -0.15522839,  0.10349658, -0.11891693],
      dtype=float32)

In [9]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:114: RuntimeWarning: No frequency information for token: flkdsjfq. It is not used to compute the SIF-embedding of phrase: flkdsjfq lkdsjfqlkdsjfq.
  RuntimeWarning,
/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:114: RuntimeWarning: No frequency information for token: lkdsjfqlkdsjfq. It is not used to compute the SIF-embedding of phrase: flkdsjfq lkdsjfqlkdsjfq.
  RuntimeWarning,
/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:132: RuntimeWarning: Unable to compute an embedding for phrase: flkdsjfq lkdsjfqlkdsjfq.
  RuntimeWarning,


In [18]:
model = Embeddings("spaCy", "en_core_web_md")

In [19]:
model.get_vector('hello world')

array([ 2.68188622e-02,  3.53879556e-02, -4.34254110e-02,  4.75675054e-03,
        9.10802633e-02, -1.13465479e-02,  6.55256882e-02,  1.03607133e-03,
       -2.78045572e-02,  3.84166837e-01, -6.51115924e-02, -1.16057299e-01,
        2.09253374e-02, -2.42254790e-02,  1.38892299e-02, -1.94349904e-02,
       -6.69198483e-02,  2.07126632e-01, -1.89200125e-03,  1.29518565e-02,
       -9.41589940e-03,  1.87474042e-02, -1.35416193e-02,  3.24031152e-02,
        2.09506648e-03, -4.12244461e-02,  4.01530042e-02, -2.37245820e-02,
        1.44139258e-02,  7.99122155e-02,  2.42089052e-02,  3.61521766e-02,
       -3.76567170e-02, -2.37567872e-02,  2.49137101e-03, -4.71429266e-02,
       -4.91942093e-03, -4.47609499e-02, -1.88785256e-03,  3.00514903e-02,
        4.26611900e-02, -4.32648137e-02, -2.47984268e-02, -3.30690877e-03,
       -3.85201834e-02,  1.21115372e-02, -9.42070317e-03, -1.60999149e-02,
        5.17858081e-02, -2.38250233e-02, -2.90761180e-02,  5.75286262e-02,
       -7.46931061e-02, -

In [20]:
model.get_vector('hello')

array([ 0.04516839,  0.01821557, -0.12080169,  0.03780054,  0.07785296,
        0.02961105,  0.08638971, -0.14539163,  0.00739668,  0.14052269,
       -0.01393681, -0.11872344,  0.02620637, -0.05242885, -0.04562486,
        0.00345355, -0.03627541,  0.17584042,  0.005068  , -0.01454883,
       -0.02173124,  0.02349623, -0.03159085,  0.02426595, -0.02928705,
       -0.04040864,  0.00984636, -0.03635238,  0.0370863 ,  0.01714602,
        0.04024217,  0.03855236, -0.05903951, -0.02191203, -0.07165759,
       -0.01420961, -0.03572587, -0.00269994, -0.0141663 , -0.03245723,
        0.03702007, -0.06479274, -0.05503337, -0.04371666, -0.04137348,
        0.01753893,  0.02618847, -0.01123043,  0.07685411, -0.01396921,
       -0.03513336,  0.11651988, -0.04082572, -0.05425291, -0.02234522,
       -0.03144764, -0.02622606,  0.027497  , -0.05283877,  0.027028  ,
       -0.09259225, -0.00600813, -0.04136632, -0.1402148 ,  0.00322729,
       -0.02813783,  0.00410459,  0.08885641,  0.00523143,  0.01

In [21]:
model.get_vector("flkdsjfq hello")

array([ 0.04516839,  0.01821557, -0.12080169,  0.03780054,  0.07785296,
        0.02961105,  0.08638971, -0.14539163,  0.00739668,  0.14052269,
       -0.01393681, -0.11872344,  0.02620637, -0.05242885, -0.04562486,
        0.00345355, -0.03627541,  0.17584042,  0.005068  , -0.01454883,
       -0.02173124,  0.02349623, -0.03159085,  0.02426595, -0.02928705,
       -0.04040864,  0.00984636, -0.03635238,  0.0370863 ,  0.01714602,
        0.04024217,  0.03855236, -0.05903951, -0.02191203, -0.07165759,
       -0.01420961, -0.03572587, -0.00269994, -0.0141663 , -0.03245723,
        0.03702007, -0.06479274, -0.05503337, -0.04371666, -0.04137348,
        0.01753893,  0.02618847, -0.01123043,  0.07685411, -0.01396921,
       -0.03513336,  0.11651988, -0.04082572, -0.05425291, -0.02234522,
       -0.03144764, -0.02622606,  0.027497  , -0.05283877,  0.027028  ,
       -0.09259225, -0.00600813, -0.04136632, -0.1402148 ,  0.00322729,
       -0.02813783,  0.00410459,  0.08885641,  0.00523143,  0.01

In [13]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

In [14]:
model = Embeddings("TensorFlow_USE","https://tfhub.dev/google/universal-sentence-encoder/4")

2022-03-02 18:13:55.542848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-02 18:13:55.543162: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-02 18:13:55.543219: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-03-02 18:13:55.543261: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-03-02 18:13:55.544532: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [15]:
model.get_vector('hello world')

array([-2.60742642e-02, -8.46000165e-02, -2.67866217e-02,  5.67842275e-02,
        6.19704723e-02,  3.82260159e-02,  2.01149341e-02,  2.74087600e-02,
        8.69831964e-02,  3.07917856e-02,  4.10411730e-02,  2.55183429e-02,
        9.65186744e-04,  5.89279719e-02,  4.00954112e-02,  4.67089340e-02,
       -3.31279561e-02,  4.07041609e-02, -1.19929705e-02, -4.76170555e-02,
       -8.29668250e-03,  7.05467463e-02,  4.84353630e-03,  8.09824839e-02,
       -5.70177287e-02, -6.43551499e-02,  6.97147325e-02, -6.98838457e-02,
        2.64606178e-02, -2.35220529e-02,  5.52375242e-02,  4.91363965e-02,
        5.69897220e-02, -6.10719360e-02,  3.60850990e-02,  2.32446156e-02,
        5.60175255e-02, -1.09551996e-02,  4.21308316e-02, -1.76953934e-02,
        7.12434668e-03,  2.04703063e-02, -7.10126385e-02, -8.45577493e-02,
        4.36058566e-02,  4.79397736e-02, -9.01802033e-02, -6.87343776e-02,
        1.27959633e-02,  1.62498504e-02, -4.83130850e-02,  3.08831818e-02,
        7.43837189e-03,  

In [16]:
model.get_vector("flkdsjfq hello")

array([-1.61078330e-02, -3.95087600e-02, -1.39619252e-02,  2.56728642e-02,
        8.09617266e-02, -2.13366398e-03,  1.76181663e-02, -4.93460633e-02,
        2.14030202e-02,  6.49608299e-02,  7.26900697e-02,  3.52026038e-02,
        3.61591950e-03, -2.11539883e-02, -1.79859679e-02, -7.07515627e-02,
        3.40879112e-02, -1.96272284e-02,  6.15902431e-02, -4.61098738e-02,
       -4.34616357e-02,  5.51219098e-02, -2.72911731e-02,  6.12010695e-02,
       -9.04980004e-02,  6.10968098e-02, -2.82148682e-02, -5.15173748e-02,
       -2.57091448e-02,  9.74511437e-04,  5.62497303e-02,  3.42172273e-02,
       -2.98734638e-03, -4.62196469e-02, -2.87835039e-02,  8.95429496e-03,
       -9.34934150e-03,  1.81295199e-03,  6.27629310e-02, -8.50399770e-03,
       -4.35009412e-02,  2.20446922e-02,  3.88210826e-03, -4.99927476e-02,
       -5.36756627e-02,  6.19914196e-02, -3.61999273e-02, -6.71657398e-02,
       -7.82451220e-03,  3.29348147e-02,  1.18287373e-03, -6.01454005e-02,
       -1.34667372e-02, -

In [17]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

array([ 7.59284794e-02, -4.77253413e-03,  4.52292264e-02,  8.38228688e-02,
        8.12911913e-02, -3.82415578e-02,  3.57003398e-02,  1.32179363e-02,
        2.07592621e-02,  5.53369857e-02,  5.01221493e-02, -3.14685050e-03,
       -1.85802188e-02, -6.11997359e-02, -1.32338554e-02, -1.64616741e-02,
        4.31338996e-02,  2.05641240e-02,  4.50077541e-02, -7.85359442e-02,
       -8.54248330e-02,  6.65055364e-02, -3.87487598e-02, -2.25983467e-02,
       -7.09450319e-02,  6.83507025e-02,  6.73124800e-03, -4.66580950e-02,
       -3.37979794e-02,  1.69156455e-02,  4.20126272e-03, -2.77005918e-02,
       -3.84362042e-02,  5.88898547e-02,  5.89574426e-02, -1.91810131e-02,
       -7.36284107e-02,  3.71947214e-02,  1.99356060e-02, -2.91928314e-02,
        8.28800630e-03,  4.55748960e-02, -1.41903600e-02, -4.60618250e-02,
       -3.16745751e-02, -3.37758921e-02, -7.12714121e-02, -5.96334971e-03,
       -1.63268615e-02,  5.46529591e-02,  4.66177538e-02, -2.97865551e-02,
        3.21516544e-02,  