## Some tests for embeddings

In [1]:
from relatio._embeddings import Embeddings

2022-03-04 14:34:52.841142: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-04 14:34:52.841161: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
model = Embeddings("Gensim_pretrained", "glove-twitter-25")

In [3]:
model.get_vector('hello world')

array([-0.07471786,  0.02505993,  0.02053264, -0.02447855, -0.06980739,
       -0.06906321,  0.41509545,  0.14673875, -0.11010275, -0.00789614,
       -0.05643118,  0.02131934, -0.8449067 ,  0.03017564, -0.067238  ,
       -0.05375415,  0.03251113, -0.07668394, -0.02830008,  0.08461264,
       -0.08671761, -0.11458462, -0.12194471, -0.01001229, -0.02754919],
      dtype=float32)

In [4]:
model.get_vector("flkdsjfq hello")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:281: RuntimeWarning: No vector for token: flkdsjfq. It is not used to compute the embedding of: flkdsjfq hello.
  RuntimeWarning,


array([-0.18157847,  0.03022106,  0.07807245,  0.00119906, -0.11215979,
       -0.11807584,  0.4377542 ,  0.25030681, -0.13314278,  0.03140144,
       -0.09876093, -0.03344414, -0.67277026, -0.13460353, -0.03161349,
       -0.10583851,  0.11448286, -0.15264852, -0.19846898,  0.14529528,
       -0.04670635, -0.1365732 , -0.1552284 ,  0.1034966 , -0.11891694],
      dtype=float32)

In [5]:
model.get_vector("flkdsjfq")

/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:281: RuntimeWarning: No vector for token: flkdsjfq. It is not used to compute the embedding of: flkdsjfq.
  RuntimeWarning,
/home/germain/Desktop/narratives/relatio/.tox/dev/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/germain/Desktop/narratives/relatio/.tox/dev/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/germain/Desktop/narratives/relatio/relatio/_embeddings.py:132: RuntimeWarning: Unable to compute an embedding for phrase: flkdsjfq.
  f"Unable to compute an embedding for phrase: {phrase}.", RuntimeWarning


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [10]:
a = model._get_vectors(["flkdsjfq", "flkdsjfq hello"])
b = model._get_vectors(["hello world", "world", "hello"])
from relatio._embeddings import _embeddings_similarity
_embeddings_similarity(a, b, threshold = 100)

(array([1]), array([2]))

In [ ]:
model = Embeddings("Gensim_pretrained", "glove-twitter-25", sentences = ["this is a nice world","hello world","hello everybody"])

In [ ]:
model.get_vector('hello world')

In [ ]:
model.get_vector("flkdsjfq hello")

In [ ]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

In [ ]:
model = Embeddings("spaCy", "en_core_web_md")

In [ ]:
model.get_vector('hello world')

In [ ]:
model.get_vector('hello')

In [ ]:
model.get_vector("flkdsjfq hello")

In [ ]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

In [ ]:
model = Embeddings("TensorFlow_USE","https://tfhub.dev/google/universal-sentence-encoder/4")

In [ ]:
model.get_vector('hello world')

In [ ]:
model.get_vector("flkdsjfq hello")

In [ ]:
model.get_vector("flkdsjfq lkdsjfqlkdsjfq")

In [3]:
import numpy as np
a = np.empty((2,300))
a[:] = np.nan
c = np.random.rand(2,300)
a = np.concatenate((a,c))
b = np.random.rand(2,300)

print(a.shape)
print(b.shape)
print(a)
print(b)

(4, 300)
(2, 300)
[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [0.38223019 0.83744666 0.17712861 ... 0.66332494 0.45095805 0.50902262]
 [0.51825497 0.73710419 0.45378035 ... 0.32435985 0.54707058 0.30382198]]
[[7.69026084e-01 4.84011283e-01 5.78765504e-03 7.37359465e-01
  9.79806170e-01 7.26996453e-01 3.47093340e-02 7.06715550e-01
  7.54931508e-01 5.53037086e-01 4.32666555e-01 8.94936733e-01
  2.96012921e-01 7.17418203e-01 7.38592093e-02 2.69897544e-01
  6.06340557e-01 1.56692678e-02 1.47145772e-01 3.53841798e-01
  7.06288542e-01 8.78248421e-01 7.23566149e-01 8.84738458e-01
  7.37433885e-01 3.72437647e-01 3.57511102e-01 1.34984227e-02
  8.95509762e-01 4.27967084e-02 4.43715593e-01 5.93427467e-01
  1.44761663e-01 2.80550381e-01 6.18687108e-01 2.15366073e-01
  4.88360962e-01 9.11391265e-02 1.66313414e-01 3.63594225e-01
  8.60522690e-01 6.25025013e-01 3.95078392e-01 4.96407478e-01
  8.452

In [9]:
print(a[~np.isnan(a).any(axis=1)].shape)

(2, 300)


In [2]:
a = np.empty((2,300))
a[:] = np.nan
print(a)

[[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan 

In [ ]:
from relatio._embeddings import _compute_distances
distances = _compute_distances(a,b)
print(distances)

In [ ]:
from relatio._embeddings import _get_min_distances
_get_min_distances(distances)

In [ ]:
from relatio._embeddings import _get_index_min_distances
_get_index_min_distances(distances)

In [ ]:
from relatio._embeddings import _embeddings_similarity
_embeddings_similarity(a, b, threshold = 10)

In [ ]:
a.shape[0]

In [3]:
import spacy 
nlp = spacy.load('en_core_web_trf')
nlp('This is a sentence').vector

array([], dtype=float32)